car:
  threshold: 30
path:
  users: parking-ms/src/main/resources/users.json
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://host.docker.internal:1433;databaseName=parking_db
    username: sa
    password: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

