car:
  threshold: 30
path:
  users: parking-ms/src/main/resources/users.json
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=parking_db
    username: sa
    password: sa

